#!/usr/bin/env bash
# file-protection.sh
# PreToolUse hook for Write/Edit/MultiEdit AND Bash — blocks writes to sensitive files.
# Prevents accidental exposure of credentials and protected configurations.
#
# Edit/Write/MultiEdit branch: checks .tool_input.file_path.
# Bash branch: catches shell-side writes the file-tool matcher never sees —
# redirection (>, >>, >|), tee, in-place sed (-i), cp/mv destinations, dd of=,
# and interpreter-mediated writes (python/node/perl/ruby/php opening a protected
# file for writing, an awk program redirecting `print` into one).
# Read-only access to protected files (cat/grep/cp FROM them) stays allowed.
# Heredoc bodies and quoted string literals are scrubbed before extraction
# (they are data, not syntax) — a deliberately QUOTED redirect target
# (`> ".env"`) is therefore a documented miss, accepted to avoid hard-blocking
# benign commands that merely mention protected names in strings. The one
# quoted position that IS syntax is an interpreter payload (`sh -c "..."`,
# `eval "..."`): those are extracted before the scrub and this guard re-runs on
# each one.
#
# Per-project allowlist: .geniro/safety.json (in cwd or any ancestor) can opt out
# of specific patterns by listing pattern IDs in the "allow_patterns" array.
#
# Schema:
#   {
#     "allow_patterns": ["write-env", "write-lockfile"]
#   }
#
# Pattern IDs: write-env, write-git-internal, write-lockfile, write-cert-key,
#              write-credentials, write-tfstate, write-vault

set -euo pipefail

# Fail open but LOUDLY if jq is missing: without it the hook cannot parse tool
# input, and a silent exit 0 would leave the user believing the guard is active.
if ! command -v jq >/dev/null 2>&1; then
  printf '{"systemMessage":"Geniro guard inactive: jq not found on PATH, so sensitive-file writes are NOT being checked. Install jq to restore the guard."}\n'
  exit 0
fi

# Consume stdin - REQUIRED first step
INPUT=$(cat)

TOOL_NAME=$(printf '%s' "$INPUT" | jq -r '.tool_name // ""' 2>/dev/null || echo "")

# Find the nearest .geniro/safety.json walking up from cwd
find_safety_json() {
  local dir="$PWD"
  while [ "$dir" != "/" ]; do
    if [ -f "$dir/.geniro/safety.json" ]; then
      echo "$dir/.geniro/safety.json"
      return 0
    fi
    dir=$(dirname "$dir")
  done
  return 1
}

ALLOWED=""
SAFETY_FILE=$(find_safety_json 2>/dev/null || true)
if [ -n "$SAFETY_FILE" ] && [ -f "$SAFETY_FILE" ]; then
  ALLOWED=$(jq -r '.allow_patterns[]? // empty' "$SAFETY_FILE" 2>/dev/null | tr '\n' ' ' || echo "")
fi

is_allowed() {
  local pattern_id="$1"
  case " $ALLOWED " in
    *" $pattern_id "*) return 0 ;;
    *) return 1 ;;
  esac
}

block() {
  local pattern_id="$1"
  local description="$2"
  local path="$3"
  echo "File protection [$pattern_id]: Cannot write to $description: $path" >&2
  if [ -n "$SAFETY_FILE" ]; then
    echo "To allow this pattern, add \"$pattern_id\" to allow_patterns in $SAFETY_FILE" >&2
  else
    echo "To allow this pattern in this project, create .geniro/safety.json with: {\"allow_patterns\": [\"$pattern_id\"]}" >&2
  fi
  exit 2
}

# Run the full pattern set against one candidate path (case-insensitive).
# Order matters: more specific patterns first.
check_protected_path() {
  local p="$1"
  local p_lower
  p_lower=$(printf '%s' "$p" | tr '[:upper:]' '[:lower:]')

  # 1. .env files (most common false-positive — dev-setup workflows often clone .env from a template)
  if ! is_allowed "write-env"; then
    if printf '%s' "$p_lower" | grep -qE '\.env$|\.env\.'; then
      block "write-env" ".env file" "$p"
    fi
  fi

  # 2. Git internals
  if ! is_allowed "write-git-internal"; then
    if printf '%s' "$p_lower" | grep -qE '\.git/'; then
      block "write-git-internal" "git internal file" "$p"
    fi
  fi

  # 3. Lock files (auto-generated by package managers — manual edits usually wrong)
  if ! is_allowed "write-lockfile"; then
    if printf '%s' "$p_lower" | grep -qE 'pnpm-lock\.yaml$|package-lock\.json$|yarn\.lock$|bun\.lockb$|cargo\.lock$|gemfile\.lock$|composer\.lock$|poetry\.lock$|pipfile\.lock$|go\.sum$'; then
      block "write-lockfile" "package-manager lock file" "$p"
    fi
  fi

  # 4. Certificates and private keys
  if ! is_allowed "write-cert-key"; then
    if printf '%s' "$p_lower" | grep -qE '\.pem$|\.key$|private-key'; then
      block "write-cert-key" "certificate or private key file" "$p"
    fi
  fi

  # 5. Credential / secret files
  if ! is_allowed "write-credentials"; then
    # Anchor to a path-segment boundary so a file literally named credentials.*
    # or secrets.* is blocked, without false-positiving on names that merely
    # contain the substring (e.g. the plugin's own lib/redact-secrets.sh).
    if printf '%s' "$p_lower" | grep -qE '(^|/)(credentials|secrets)\.'; then
      block "write-credentials" "credentials/secrets file" "$p"
    fi
  fi

  # 6. Terraform state
  if ! is_allowed "write-tfstate"; then
    if printf '%s' "$p_lower" | grep -qE '\.tfstate'; then
      block "write-tfstate" "Terraform state file" "$p"
    fi
  fi

  # 7. Vault files
  if ! is_allowed "write-vault"; then
    if printf '%s' "$p_lower" | grep -qE '\.vault'; then
      block "write-vault" "Vault file" "$p"
    fi
  fi
}

if [ "$TOOL_NAME" = "Bash" ]; then
  # ---- Bash branch: shell-side writes into protected paths ----
  COMMAND=$(printf '%s' "$INPUT" | jq -r '.tool_input.command // ""' 2>/dev/null || echo "")
  if [ -z "$COMMAND" ]; then
    exit 0
  fi
  # Heredoc bodies are DATA, not shell syntax — a `> .env` inside one is text.
  # Drop body lines (between <<TAG / <<-TAG / <<'TAG' and the closing TAG)
  # before any extraction; the line carrying the << operator itself is kept, so
  # `cat <<EOF > .env` still yields its redirect target.
  SCRUBBED=$(printf '%s\n' "$COMMAND" | awk '
    hd {
      line = $0
      if (dash) sub(/^\t+/, "", line)   # <<- strips leading TABS from the terminator
      if (line == tag) hd = 0
      next
    }
    match($0, /<<-?[[:space:]]*["'\'']?[A-Za-z_][A-Za-z0-9_]*/) {
      tag = substr($0, RSTART, RLENGTH)
      dash = (tag ~ /^<<-/)
      sub(/^<<-?[[:space:]]*/, "", tag)
      gsub(/["'\'']/, "", tag)
      hd = 1
      print
      next
    }
    { print }
  ')

  # Interpreter indirection: `sh -c "<payload>"` (or bash/zsh/dash -lc, ...) and
  # `eval "<payload>"` run <payload> as a command, but the quote-scrub below
  # would treat it as data and miss a write into a protected path inside it.
  # Extraction is single-sourced in lib/write-vectors.sh; the inline fallback
  # keeps the guard recursing on a vendored install shipping hooks/ without
  # lib/ — a missing helper must never make this guard fail open.
  _geniro_wv_helper="${CLAUDE_PLUGIN_ROOT:-.}/lib/write-vectors.sh"
  if [ -f "$_geniro_wv_helper" ]; then
    # shellcheck source=/dev/null
    source "$_geniro_wv_helper" 2>/dev/null || true
  fi
  if ! command -v _geniro_extract_inner_payloads >/dev/null 2>&1; then
    _geniro_extract_inner_payloads() {
      local cmd="${1:-}"
      if [ -z "$cmd" ]; then return 0; fi
      local _m _pl
      while IFS= read -r _m; do
        [ -z "$_m" ] && continue
        _pl=$(printf '%s' "$_m" | sed -E 's/^.*[[:space:]]-[A-Za-z]*c[A-Za-z]*[[:space:]]+//')
        _pl="${_pl#\"}"; _pl="${_pl%\"}"; _pl="${_pl#\'}"; _pl="${_pl%\'}"
        [ -n "$_pl" ] && printf '%s\n' "$_pl"
      done <<< "$(printf '%s\n' "$cmd" | grep -oE '(^|[^[:alnum:]_/])(sh|bash|zsh|dash|ksh|ash)[[:space:]]+-[A-Za-z]*c[A-Za-z]*[[:space:]]+("[^"]*"|'\''[^'\'']*'\''|[^[:space:];|&]+)' 2>/dev/null || true)"
      while IFS= read -r _m; do
        [ -z "$_m" ] && continue
        _pl=$(printf '%s' "$_m" | sed -E 's/^[^[:alnum:]_]?eval[[:space:]]+//')
        _pl="${_pl#\"}"; _pl="${_pl%\"}"; _pl="${_pl#\'}"; _pl="${_pl%\'}"
        [ -n "$_pl" ] && printf '%s\n' "$_pl"
      done <<< "$(printf '%s\n' "$cmd" | grep -oE '(^|[^[:alnum:]_/-])eval[[:space:]]+("[^"]*"|'\''[^'\'']*'\''|[^[:space:];|&]+)' 2>/dev/null || true)"
      return 0
    }
  fi
  if ! command -v _geniro_interp_write_targets >/dev/null 2>&1; then
    # Degraded stand-in on a vendored install: literal targets only (no variable
    # resolution), rc=10 for every other write op so the caller still scans.
    _geniro_interp_write_targets() {
      local c="${1:-}" q="\\\\?[\"']"
      printf '%s' "$c" | grep -qE '(^|[|;&[:space:]]|/)(python[0-9.]*|node|perl|ruby|php|awk|gawk|mawk)([[:space:]]|$)' || return 0
      printf '%s' "$c" | grep -oE "(open|fopen|File\.open)\([[:space:]]*${q}[^\\\\\"']+${q}[[:space:]]*,[[:space:]]*${q}[waxWAX>]|(writeFileSync|appendFileSync|createWriteStream|writeFile|file_put_contents|File\.write|IO\.write)\([[:space:]]*${q}[^\\\\\"']+${q}|(print|printf)[^;}]*>{1,2}[[:space:]]*${q}[^\\\\\"']+${q}" 2>/dev/null \
        | sed -E "s/^.*[(>][[:space:]]*\\\\?[\"']//; s/\\\\?[\"'].*\$//" || true
      if printf '%s' "$c" | grep -qE "open\([^)]*,[[:space:]]*${q}[waxWAX>]|(write_text|write_bytes|writeFileSync|appendFileSync|createWriteStream|writeFile|file_put_contents|File\.write|IO\.write)\("; then
        return 10
      fi
      return 0
    }
  fi
  if ! command -v _geniro_wv_path_tokens >/dev/null 2>&1; then
    _geniro_wv_path_tokens() {
      printf '%s' "${1:-}" | grep -oE '[^[:space:]"'\''`=(),;|&<>{}]+' 2>/dev/null \
        | grep -E '/|\.[A-Za-z0-9]{1,6}$' 2>/dev/null | grep -vE '^-' 2>/dev/null || true
      return 0
    }
  fi

  # Re-run THIS guard on each extracted payload (unblanked); a block inside
  # propagates out. Nested indirection terminates because each payload is
  # strictly shorter than the command it came from.
  _geniro_self="${BASH_SOURCE[0]:-$0}"
  INNER_PAYLOADS=$(_geniro_extract_inner_payloads "$SCRUBBED")
  if [ -n "$INNER_PAYLOADS" ]; then
    while IFS= read -r _pl; do
      [ -z "$_pl" ] && continue
      if ! printf '%s' "$_pl" | jq -Rs '{tool_name: "Bash", tool_input: {command: .}}' | bash "$_geniro_self"; then
        exit 2
      fi
    done <<< "$INNER_PAYLOADS"
  fi

  # Join backslash-newline continuations, then collapse newlines (mirrors
  # block-dangerous-git.sh) so multi-line commands can't split a write apart.
  JOINED="${SCRUBBED//\\$'\n'/ }"
  ONELINE="${JOINED//$'\n'/ }"

  # Quoted string literals are also data (`echo "see > .env"` writes nothing).
  # Blank them out before extraction. Trade-off: a deliberately QUOTED redirect
  # target (`> ".env"`) is no longer caught — accepted; the accidental
  # overwrite shapes this guard exists for are unquoted.
  ONELINE=$(printf '%s' "$ONELINE" | sed -E "s/'[^']*'/ /g; s/\"[^\"]*\"/ /g")

  CANDIDATES=""
  add_candidate() {
    local c="$1"
    # Trim one layer of surrounding quotes so >"$F"-style targets normalize.
    c="${c#\"}"; c="${c%\"}"
    c="${c#\'}"; c="${c%\'}"
    if [ -n "$c" ]; then
      CANDIDATES="${CANDIDATES}${c}
"
    fi
  }

  # 1) Redirection targets: > file, >> file, >| file. fd-dups (>&2) never yield
  #    a target (the class excludes &); 2>/dev/null lands on /dev/null, which
  #    matches no protected pattern.
  while IFS= read -r tok; do
    [ -z "$tok" ] && continue
    add_candidate "$(printf '%s' "$tok" | sed -E 's/^>{1,2}\|?[[:space:]]*//')"
  done <<< "$(printf '%s' "$ONELINE" | grep -oE '>{1,2}\|?[[:space:]]*[^[:space:];|&<>)]+' || true)"

  # 2) tee: every non-flag argument of a tee invocation is written to.
  while IFS= read -r span; do
    [ -z "$span" ] && continue
    set -f
    # shellcheck disable=SC2086
    for tok in $span; do
      case "$tok" in *tee|-*) continue ;; esac
      add_candidate "$tok"
    done
    set +f
  done <<< "$(printf '%s' "$ONELINE" | grep -oE '(^|[|;&[:space:]])tee[[:space:]]+[^|;&]*' || true)"

  # 3) In-place sed: file arguments of a `sed -i` span are overwritten. An
  #    UNQUOTED script token (s/.../.../, y|...|...) is skipped — it is sed
  #    code, not a path, and a substitution that merely MENTIONS a protected
  #    name (s/.env.a/.env.b/) must not block; quoted scripts were already
  #    blanked by the quote scrub above.
  while IFS= read -r span; do
    [ -z "$span" ] && continue
    printf '%s' "$span" | grep -qE '[[:space:]]-i|[[:space:]]--in-place' || continue
    set -f
    # shellcheck disable=SC2086
    for tok in $span; do
      case "$tok" in
        *sed|-*) continue ;;
        s[!a-zA-Z0-9]*|y[!a-zA-Z0-9]*) continue ;;
      esac
      add_candidate "$tok"
    done
    set +f
  done <<< "$(printf '%s' "$ONELINE" | grep -oE '(^|[|;&[:space:]])sed[[:space:]]+[^|;&]*' || true)"

  # 4) cp/mv: only the DESTINATION (last non-flag token) is a write — copying
  #    FROM a protected file is a read and stays allowed.
  while IFS= read -r span; do
    [ -z "$span" ] && continue
    last=""
    set -f
    # shellcheck disable=SC2086
    for tok in $span; do
      case "$tok" in -*) continue ;; esac
      last="$tok"
    done
    set +f
    case "$last" in ""|cp|mv|*/cp|*/mv) : ;; *) add_candidate "$last" ;; esac
  done <<< "$(printf '%s' "$ONELINE" | grep -oE '(^|[|;&[:space:]])(cp|mv)[[:space:]]+[^|;&]*' || true)"

  # 5) dd of=target
  while IFS= read -r tok; do
    [ -z "$tok" ] && continue
    add_candidate "${tok#of=}"
  done <<< "$(printf '%s' "$ONELINE" | grep -oE 'of=[^[:space:];|&]+' || true)"

  # 6) truncate -s <size> FILE... — each FILE is emptied/rewritten. Skip the size
  #    operand (the token after -s/--size) and a -r/--reference source.
  while IFS= read -r span; do
    [ -z "$span" ] && continue
    set -f
    skip_next=0
    # shellcheck disable=SC2086
    for tok in $span; do
      if [ "$skip_next" = "1" ]; then skip_next=0; continue; fi
      case "$tok" in
        *truncate) continue ;;
        -s|--size|-r|--reference) skip_next=1; continue ;;
        -*) continue ;;
      esac
      add_candidate "$tok"
    done
    set +f
  done <<< "$(printf '%s' "$ONELINE" | grep -oE '(^|[|;&[:space:]])truncate[[:space:]]+[^|;&]*' || true)"

  # 7) shred FILE... — destroys/overwrites each FILE in place. Skip -n/-s count
  #    and size operands.
  while IFS= read -r span; do
    [ -z "$span" ] && continue
    set -f
    skip_next=0
    # shellcheck disable=SC2086
    for tok in $span; do
      if [ "$skip_next" = "1" ]; then skip_next=0; continue; fi
      case "$tok" in
        *shred) continue ;;
        -n|--iterations|-s|--size) skip_next=1; continue ;;
        -*) continue ;;
      esac
      add_candidate "$tok"
    done
    set +f
  done <<< "$(printf '%s' "$ONELINE" | grep -oE '(^|[|;&[:space:]])shred[[:space:]]+[^|;&]*' || true)"

  # 8) install / rsync SRC... DEST — the DEST (last non-flag token) is written,
  #    like cp/mv; an install `-t DIR` / `--target-directory DIR` writes into DIR.
  while IFS= read -r span; do
    [ -z "$span" ] && continue
    last=""
    tgt_dir=""
    take_dir=0
    set -f
    # shellcheck disable=SC2086
    for tok in $span; do
      if [ "$take_dir" = "1" ]; then tgt_dir="$tok"; take_dir=0; continue; fi
      case "$tok" in
        install|rsync|*/install|*/rsync) continue ;;
        -t|--target-directory) take_dir=1; continue ;;
        --target-directory=*) tgt_dir="${tok#--target-directory=}"; continue ;;
        -*) continue ;;
      esac
      last="$tok"
    done
    set +f
    if [ -n "$tgt_dir" ]; then
      # install -t DIR form: DIR is the write target; trailing tokens are sources.
      add_candidate "$tgt_dir"
    else
      case "$last" in ""|install|rsync|*/install|*/rsync) : ;; *) add_candidate "$last" ;; esac
    fi
  done <<< "$(printf '%s' "$ONELINE" | grep -oE '(^|[|;&[:space:]])(install|rsync)[[:space:]]+[^|;&]*' || true)"

  # 9) ln -f ... LINK — the LINK (last non-flag token) is created/overwritten
  #    when -f/--force is present (without -f, ln refuses to clobber an existing
  #    target). A symlink or hardlink over a protected path is a write.
  while IFS= read -r span; do
    [ -z "$span" ] && continue
    printf '%s' "$span" | grep -qE '[[:space:]]-[a-zA-Z]*f|[[:space:]]--force' || continue
    last=""
    set -f
    # shellcheck disable=SC2086
    for tok in $span; do
      case "$tok" in ln|*/ln|-*) continue ;; esac
      last="$tok"
    done
    set +f
    case "$last" in ""|ln|*/ln) : ;; *) add_candidate "$last" ;; esac
  done <<< "$(printf '%s' "$ONELINE" | grep -oE '(^|[|;&[:space:]])ln[[:space:]]+[^|;&]*' || true)"

  # 10) Interpreter-mediated writes: python/node/perl/ruby/php opening a file for
  #     writing, or an awk program redirecting `print` into one. Vectors 1-9 read
  #     $ONELINE, whose heredoc bodies and quoted literals were blanked as data —
  #     and an interpreter's file write is not shell syntax anywhere, so
  #     `python3 -c "open('.env','w').write(k)"` reaches the filesystem
  #     unchecked. This vector therefore scans the RAW $COMMAND, and fires only
  #     on the conjunction interpreter + write op + target, so a read-only
  #     interpreter call stays allowed. Contract: lib/write-vectors.sh.
  _iw_unresolved=0
  _iw_targets=$(_geniro_interp_write_targets "$COMMAND") || _iw_unresolved=1
  if [ -n "$_iw_targets" ]; then
    while IFS= read -r tok; do
      [ -z "$tok" ] && continue
      add_candidate "$tok"
    done <<< "$_iw_targets"
  fi
  if [ "$_iw_unresolved" = "1" ]; then
    # The write target is a variable or expression (`open(p,'w')`), unresolvable
    # from the command text. Fall back to every path-shaped token in it: the
    # protected patterns are distinctive filenames, so a token that is not one of
    # them costs nothing, while `p='.env'; open(p,'w')` still lands.
    while IFS= read -r tok; do
      [ -z "$tok" ] && continue
      add_candidate "$tok"
    done <<< "$(_geniro_wv_path_tokens "$COMMAND")"
  fi

  if [ -z "$CANDIDATES" ]; then
    exit 0
  fi
  while IFS= read -r cand; do
    [ -z "$cand" ] && continue
    check_protected_path "$cand"
  done <<< "$CANDIDATES"
  exit 0
fi

# ---- Edit/Write/MultiEdit branch ----
FILE_PATH=$(printf '%s' "$INPUT" | jq -r '.tool_input.file_path // .tool_input.notebook_path // ""' 2>/dev/null || echo "")

if [ -z "$FILE_PATH" ]; then
  # No file path found, allow execution
  exit 0
fi

check_protected_path "$FILE_PATH"

# File is safe to write, allow execution
exit 0
