#!/usr/bin/env bash
# file-protection.sh
# PreToolUse hook for Write/Edit/MultiEdit AND Bash — blocks writes to sensitive files.
# Prevents accidental exposure of credentials and protected configurations.
#
# Edit/Write/MultiEdit branch: checks .tool_input.file_path.
# Bash branch: catches shell-side writes the file-tool matcher never sees —
# redirection (>, >>, >|), tee, in-place sed (-i), cp/mv destinations, dd of=.
# Read-only access to protected files (cat/grep/cp FROM them) stays allowed.
# Heredoc bodies and quoted string literals are scrubbed before extraction
# (they are data, not syntax) — a deliberately QUOTED redirect target
# (`> ".env"`) is therefore a documented miss, accepted to avoid hard-blocking
# benign commands that merely mention protected names in strings.
#
# Per-project allowlist: .geniro/safety.json (in cwd or any ancestor) can opt out
# of specific patterns by listing pattern IDs in the "allow_patterns" array.
#
# Schema:
#   {
#     "allow_patterns": ["write-env", "write-lockfile"]
#   }
#
# Pattern IDs: write-env, write-git-internal, write-lockfile, write-cert-key,
#              write-credentials, write-tfstate, write-vault

set -euo pipefail

# Fail open but LOUDLY if jq is missing: without it the hook cannot parse tool
# input, and a silent exit 0 would leave the user believing the guard is active.
if ! command -v jq >/dev/null 2>&1; then
  printf '{"systemMessage":"Geniro guard inactive: jq not found on PATH, so sensitive-file writes are NOT being checked. Install jq to restore the guard."}\n'
  exit 0
fi

# Consume stdin - REQUIRED first step
INPUT=$(cat)

TOOL_NAME=$(printf '%s' "$INPUT" | jq -r '.tool_name // ""' 2>/dev/null || echo "")

# Find the nearest .geniro/safety.json walking up from cwd
find_safety_json() {
  local dir="$PWD"
  while [ "$dir" != "/" ]; do
    if [ -f "$dir/.geniro/safety.json" ]; then
      echo "$dir/.geniro/safety.json"
      return 0
    fi
    dir=$(dirname "$dir")
  done
  return 1
}

ALLOWED=""
SAFETY_FILE=$(find_safety_json 2>/dev/null || true)
if [ -n "$SAFETY_FILE" ] && [ -f "$SAFETY_FILE" ]; then
  ALLOWED=$(jq -r '.allow_patterns[]? // empty' "$SAFETY_FILE" 2>/dev/null | tr '\n' ' ' || echo "")
fi

is_allowed() {
  local pattern_id="$1"
  case " $ALLOWED " in
    *" $pattern_id "*) return 0 ;;
    *) return 1 ;;
  esac
}

block() {
  local pattern_id="$1"
  local description="$2"
  local path="$3"
  echo "File protection [$pattern_id]: Cannot write to $description: $path" >&2
  if [ -n "$SAFETY_FILE" ]; then
    echo "To allow this pattern, add \"$pattern_id\" to allow_patterns in $SAFETY_FILE" >&2
  else
    echo "To allow this pattern in this project, create .geniro/safety.json with: {\"allow_patterns\": [\"$pattern_id\"]}" >&2
  fi
  exit 2
}

# Run the full pattern set against one candidate path (case-insensitive).
# Order matters: more specific patterns first.
check_protected_path() {
  local p="$1"
  local p_lower
  p_lower=$(printf '%s' "$p" | tr '[:upper:]' '[:lower:]')

  # 1. .env files (most common false-positive — dev-setup workflows often clone .env from a template)
  if ! is_allowed "write-env"; then
    if printf '%s' "$p_lower" | grep -qE '\.env$|\.env\.'; then
      block "write-env" ".env file" "$p"
    fi
  fi

  # 2. Git internals
  if ! is_allowed "write-git-internal"; then
    if printf '%s' "$p_lower" | grep -qE '\.git/'; then
      block "write-git-internal" "git internal file" "$p"
    fi
  fi

  # 3. Lock files (auto-generated by package managers — manual edits usually wrong)
  if ! is_allowed "write-lockfile"; then
    if printf '%s' "$p_lower" | grep -qE 'pnpm-lock\.yaml$|package-lock\.json$|yarn\.lock$|bun\.lockb$|cargo\.lock$|gemfile\.lock$|composer\.lock$|poetry\.lock$|pipfile\.lock$|go\.sum$'; then
      block "write-lockfile" "package-manager lock file" "$p"
    fi
  fi

  # 4. Certificates and private keys
  if ! is_allowed "write-cert-key"; then
    if printf '%s' "$p_lower" | grep -qE '\.pem$|\.key$|private-key'; then
      block "write-cert-key" "certificate or private key file" "$p"
    fi
  fi

  # 5. Credential / secret files
  if ! is_allowed "write-credentials"; then
    # Anchor to a path-segment boundary so a file literally named credentials.*
    # or secrets.* is blocked, without false-positiving on names that merely
    # contain the substring (e.g. the plugin's own lib/redact-secrets.sh).
    if printf '%s' "$p_lower" | grep -qE '(^|/)(credentials|secrets)\.'; then
      block "write-credentials" "credentials/secrets file" "$p"
    fi
  fi

  # 6. Terraform state
  if ! is_allowed "write-tfstate"; then
    if printf '%s' "$p_lower" | grep -qE '\.tfstate'; then
      block "write-tfstate" "Terraform state file" "$p"
    fi
  fi

  # 7. Vault files
  if ! is_allowed "write-vault"; then
    if printf '%s' "$p_lower" | grep -qE '\.vault'; then
      block "write-vault" "Vault file" "$p"
    fi
  fi
}

if [ "$TOOL_NAME" = "Bash" ]; then
  # ---- Bash branch: shell-side writes into protected paths ----
  COMMAND=$(printf '%s' "$INPUT" | jq -r '.tool_input.command // ""' 2>/dev/null || echo "")
  if [ -z "$COMMAND" ]; then
    exit 0
  fi
  # Heredoc bodies are DATA, not shell syntax — a `> .env` inside one is text.
  # Drop body lines (between <<TAG / <<-TAG / <<'TAG' and the closing TAG)
  # before any extraction; the line carrying the << operator itself is kept, so
  # `cat <<EOF > .env` still yields its redirect target.
  SCRUBBED=$(printf '%s\n' "$COMMAND" | awk '
    hd {
      line = $0
      if (dash) sub(/^\t+/, "", line)   # <<- strips leading TABS from the terminator
      if (line == tag) hd = 0
      next
    }
    match($0, /<<-?["'\'']?[A-Za-z_][A-Za-z0-9_]*/) {
      tag = substr($0, RSTART, RLENGTH)
      dash = (tag ~ /^<<-/)
      sub(/^<<-?/, "", tag)
      gsub(/["'\'']/, "", tag)
      hd = 1
      print
      next
    }
    { print }
  ')

  # Join backslash-newline continuations, then collapse newlines (mirrors
  # block-dangerous-git.sh) so multi-line commands can't split a write apart.
  JOINED="${SCRUBBED//\\$'\n'/ }"
  ONELINE="${JOINED//$'\n'/ }"

  # Quoted string literals are also data (`echo "see > .env"` writes nothing).
  # Blank them out before extraction. Trade-off: a deliberately QUOTED redirect
  # target (`> ".env"`) is no longer caught — accepted; the accidental
  # overwrite shapes this guard exists for are unquoted.
  ONELINE=$(printf '%s' "$ONELINE" | sed -E "s/'[^']*'/ /g; s/\"[^\"]*\"/ /g")

  CANDIDATES=""
  add_candidate() {
    local c="$1"
    # Trim one layer of surrounding quotes so >"$F"-style targets normalize.
    c="${c#\"}"; c="${c%\"}"
    c="${c#\'}"; c="${c%\'}"
    if [ -n "$c" ]; then
      CANDIDATES="${CANDIDATES}${c}
"
    fi
  }

  # 1) Redirection targets: > file, >> file, >| file. fd-dups (>&2) never yield
  #    a target (the class excludes &); 2>/dev/null lands on /dev/null, which
  #    matches no protected pattern.
  while IFS= read -r tok; do
    [ -z "$tok" ] && continue
    add_candidate "$(printf '%s' "$tok" | sed -E 's/^>{1,2}\|?[[:space:]]*//')"
  done <<< "$(printf '%s' "$ONELINE" | grep -oE '>{1,2}\|?[[:space:]]*[^[:space:];|&<>)]+' || true)"

  # 2) tee: every non-flag argument of a tee invocation is written to.
  while IFS= read -r span; do
    [ -z "$span" ] && continue
    set -f
    # shellcheck disable=SC2086
    for tok in $span; do
      case "$tok" in *tee|-*) continue ;; esac
      add_candidate "$tok"
    done
    set +f
  done <<< "$(printf '%s' "$ONELINE" | grep -oE '(^|[|;&[:space:]])tee[[:space:]]+[^|;&]*' || true)"

  # 3) In-place sed: file arguments of a `sed -i` span are overwritten. An
  #    UNQUOTED script token (s/.../.../, y|...|...) is skipped — it is sed
  #    code, not a path, and a substitution that merely MENTIONS a protected
  #    name (s/.env.a/.env.b/) must not block; quoted scripts were already
  #    blanked by the quote scrub above.
  while IFS= read -r span; do
    [ -z "$span" ] && continue
    printf '%s' "$span" | grep -qE '[[:space:]]-i' || continue
    set -f
    # shellcheck disable=SC2086
    for tok in $span; do
      case "$tok" in
        *sed|-*) continue ;;
        s[!a-zA-Z0-9]*|y[!a-zA-Z0-9]*) continue ;;
      esac
      add_candidate "$tok"
    done
    set +f
  done <<< "$(printf '%s' "$ONELINE" | grep -oE '(^|[|;&[:space:]])sed[[:space:]]+[^|;&]*' || true)"

  # 4) cp/mv: only the DESTINATION (last non-flag token) is a write — copying
  #    FROM a protected file is a read and stays allowed.
  while IFS= read -r span; do
    [ -z "$span" ] && continue
    last=""
    set -f
    # shellcheck disable=SC2086
    for tok in $span; do
      case "$tok" in -*) continue ;; esac
      last="$tok"
    done
    set +f
    case "$last" in ""|cp|mv|*/cp|*/mv) : ;; *) add_candidate "$last" ;; esac
  done <<< "$(printf '%s' "$ONELINE" | grep -oE '(^|[|;&[:space:]])(cp|mv)[[:space:]]+[^|;&]*' || true)"

  # 5) dd of=target
  while IFS= read -r tok; do
    [ -z "$tok" ] && continue
    add_candidate "${tok#of=}"
  done <<< "$(printf '%s' "$ONELINE" | grep -oE 'of=[^[:space:];|&]+' || true)"

  if [ -z "$CANDIDATES" ]; then
    exit 0
  fi
  while IFS= read -r cand; do
    [ -z "$cand" ] && continue
    check_protected_path "$cand"
  done <<< "$CANDIDATES"
  exit 0
fi

# ---- Edit/Write/MultiEdit branch ----
FILE_PATH=$(printf '%s' "$INPUT" | jq -r '.tool_input.file_path // .tool_input.notebook_path // ""' 2>/dev/null || echo "")

if [ -z "$FILE_PATH" ]; then
  # No file path found, allow execution
  exit 0
fi

check_protected_path "$FILE_PATH"

# File is safe to write, allow execution
exit 0
