#!/bin/bash
# file-protection.sh
# PreToolUse hook for Write and Edit - blocks writes to sensitive files
# Prevents accidental exposure of credentials and protected configurations.
#
# Per-project allowlist: .geniro/safety.json (in cwd or any ancestor) can opt out
# of specific patterns by listing pattern IDs in the "allow_patterns" array.
#
# Schema:
#   {
#     "allow_patterns": ["write-env", "write-lockfile"]
#   }
#
# Pattern IDs: write-env, write-git-internal, write-lockfile, write-cert-key,
#              write-credentials, write-tfstate, write-vault

set -euo pipefail

# Consume stdin - REQUIRED first step
INPUT=$(cat)

# Extract file path from tool input JSON
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // ""' 2>/dev/null || echo "")

if [ -z "$FILE_PATH" ]; then
  # No file path found, allow execution
  exit 0
fi

# Convert file path to lowercase for case-insensitive matching
FILE_PATH_LOWER=$(echo "$FILE_PATH" | tr '[:upper:]' '[:lower:]')

# Find the nearest .geniro/safety.json walking up from cwd
find_safety_json() {
  local dir="$PWD"
  while [ "$dir" != "/" ]; do
    if [ -f "$dir/.geniro/safety.json" ]; then
      echo "$dir/.geniro/safety.json"
      return 0
    fi
    dir=$(dirname "$dir")
  done
  return 1
}

ALLOWED=""
SAFETY_FILE=$(find_safety_json 2>/dev/null || true)
if [ -n "$SAFETY_FILE" ] && [ -f "$SAFETY_FILE" ]; then
  ALLOWED=$(jq -r '.allow_patterns[]? // empty' "$SAFETY_FILE" 2>/dev/null | tr '\n' ' ' || echo "")
fi

is_allowed() {
  local pattern_id="$1"
  case " $ALLOWED " in
    *" $pattern_id "*) return 0 ;;
    *) return 1 ;;
  esac
}

block() {
  local pattern_id="$1"
  local description="$2"
  echo "File protection [$pattern_id]: Cannot write to $description: $FILE_PATH" >&2
  if [ -n "$SAFETY_FILE" ]; then
    echo "To allow this pattern, add \"$pattern_id\" to allow_patterns in $SAFETY_FILE" >&2
  else
    echo "To allow this pattern in this project, create .geniro/safety.json with: {\"allow_patterns\": [\"$pattern_id\"]}" >&2
  fi
  exit 2
}

# Each check: id, regex, description.
# Order matters: more specific patterns first.

# 1. .env files (most common false-positive — dev-setup workflows often clone .env from a template)
if ! is_allowed "write-env"; then
  if echo "$FILE_PATH_LOWER" | grep -qE '\.env$|\.env\.'; then
    block "write-env" ".env file"
  fi
fi

# 2. Git internals
if ! is_allowed "write-git-internal"; then
  if echo "$FILE_PATH_LOWER" | grep -qE '\.git/'; then
    block "write-git-internal" "git internal file"
  fi
fi

# 3. Lock files (auto-generated by package managers — manual edits usually wrong)
if ! is_allowed "write-lockfile"; then
  if echo "$FILE_PATH_LOWER" | grep -qE 'pnpm-lock\.yaml$|package-lock\.json$|yarn\.lock$|bun\.lockb$|cargo\.lock$|gemfile\.lock$|composer\.lock$|poetry\.lock$|pipfile\.lock$|go\.sum$'; then
    block "write-lockfile" "package-manager lock file"
  fi
fi

# 4. Certificates and private keys
if ! is_allowed "write-cert-key"; then
  if echo "$FILE_PATH_LOWER" | grep -qE '\.pem$|\.key$|private-key'; then
    block "write-cert-key" "certificate or private key file"
  fi
fi

# 5. Credential / secret files
if ! is_allowed "write-credentials"; then
  if echo "$FILE_PATH_LOWER" | grep -qE 'credentials\.|secrets\.'; then
    block "write-credentials" "credentials/secrets file"
  fi
fi

# 6. Terraform state
if ! is_allowed "write-tfstate"; then
  if echo "$FILE_PATH_LOWER" | grep -qE '\.tfstate'; then
    block "write-tfstate" "Terraform state file"
  fi
fi

# 7. Vault files
if ! is_allowed "write-vault"; then
  if echo "$FILE_PATH_LOWER" | grep -qE '\.vault'; then
    block "write-vault" "Vault file"
  fi
fi

# File is safe to write, allow execution
exit 0
